on:
  pull_request:
    types:
      - opened
      - synchronize
    branches-ignore:
      - release-please--*
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go test '**/*_test.go'
